### ISSUE TITLE
Tests for Dutch translation

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/requirements#42]
Includes:

- [x] uncontracted braille
- [x] ~~8-dot braille~~
- [x] emphasis indicators

Addresses requirements:
- [x] [4.3:34C](http://snaekobbi.github.io/requirements#4.3:34C)
- [x] ~~[4.3:35B](http://snaekobbi.github.io/requirements#4.3:35B)~~
- [x] ~~[4.3:37C](http://snaekobbi.github.io/requirements#4.3:37C)~~
- [x] [4.3:38](http://snaekobbi.github.io/requirements#4.3:38)
- [ ] [4.3:39](http://snaekobbi.github.io/requirements#4.3:39)

**Comment by bertfrees** [comment]
Need to find out whether there is currently a definition of 8-dot braille in Dutch, and whether defining and/or implementing are in scope. If yes, what is the priority.

**Comment by dkager** [comment]
> Need to find out whether there is currently a definition of 8-dot braille in Dutch, ...

Short answer: there isn't. It would be desirable to have such a standard, but according to transcribers and other experts at Dedicon there is none yet.
Screen reader users commonly use either the German or the US English 8-dot uncontracted table.

**Comment by dkager** [comment]
Can close this: all tests except 8-dot braille are in liblouis.

**Comment by bertfrees** [comment]
About 8-dot: see also https://github.com/snaekobbi/sprints/issues/14#issuecomment-126207899.

**Comment by bertfrees** [comment]
I'd like to close this but we don't have tests for 4.3:39 yet. @dkager What do you think, should we cancel that requirement?

**Comment by dkager** [comment]
What would this look like? Something like `<p><span class="bold">Foo</span> bar.</p>`?
I haven't seen this in the wild yet. The classes that we do need to support are lsited in snaekobbi/pipeline-mod-dedicon#8. These should be doable with CSS alone. So we can probably skip 4.3:39 (for now).

**Comment by bertfrees** [comment]
It could also look like e.g. `<span style="color:red">Foo</span> bar.`.

OK we'll skip it for now. Then I can close the issue.
